#!/bin/bash
s=""
runner="hi.c"
func=$current_folder/$1
./betty/betty-style.pl $func
./betty/betty-doc.pl $func

gcc -Wall -Werror -Wextra -pedantic $runner $func -Lcustom_c -lholberton -o post
./post
