#!/bin/bash

if [ -d $current_folder ]; then
	echo "$current_folder exists in this directory."
	exit 1
fi

if [ ! -d $current_folder ]; then
	mkdir $current_folder
	cp holberton.h $current_folder
	cp README.md $current_folder
fi
