#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "Usage: '<filename>' '<prototype>'"
	exit 1
fi

if [ ! -d $current_folder ]; then
./initdir
fi

set -f
./addheader $current_folder "$2;"
./addheader . "$2;"
./create "$2" > $current_folder/$1
